namespace E.Loi.Helpers.Enumarations;

public enum LawStatu
{
    ENCOUR = 0,
    //قيد الدرس - القراءة 1 – أحيل على مكتب المجلس
    RESTRICTION_LESSON_REDING_ONE_REFER_OFFICE_COUNCIL = 1,
    //قيد الدرس - القراءة 1 – أحيل على اللجنة
    RESTRICTION_LESSON_REDING_ONE_REFER_COMMISSION = 2,
    //قيد الدرس - القراءة 1 – برمجته اللجنة
    RESTRICTION_LESSON_REDING_ONE_REFER_PROGRAMMED_IT_COMMISSION = 3,
    //قيد الدرس - القراءة 1 – صوتت عليه اللجنة
    RESTRICTION_LESSON_REDING_ONE_REFER_VOTED_COMMISSION = 4,
    //صادق عليه مجلس النواب - القراءة 1
    APPROVED_IT_HOUSE_OF_REPRESENTATIVES_READING_ONE = 5,

    RESTRICTION_LESSON_REDING_TWO_REFER_OFFICE_COUNCIL = 7,
    RESTRICTION_LESSON_REDING_TWO_REFER_COMMISSION = 8,
    RESTRICTION_LESSON_REDING_TWO_REFER_PROGRAMMED_IT_COMMISSION = 9,
    RESTRICTION_LESSON_REDING_TWO_REFER_VOTED_COMMISSION = 10,
    APPROVED_IT_HOUSE_OF_REPRESENTATIVES_READING_TWO = 11,
}
